# .bashrc
PATH=":$HOME/BIN:$PATH"

# Source global definitions
if [ -f /etc/bash.bashrc ]; then
        . /etc/bash.bashrc
fi

umask 022
ulimit -c 0
#ulimit -s unlimited

function dvips ()
{
	command dvips -O 0.0in,0.6in -o $1.ps $1
}

alias net='ssh 10.0.0.1 -l pawelg'
alias neth='ssh access.cs.ualberta.ca -l pawel'

alias k=clear
alias h=history

function apropos () 
{
	man -k $1 | more
}

function spell ()
{
	aspell list < $1 | sort -u
}

function spp ()
{
	echo $* > zzzjunkspp
	aspell list < zzzjunkspp | sort -u
	rm -f zzzjunkspp
}

function vi ()
{
	if elvis -G x11 -font 9x15 -client $* >& /dev/null
	then echo "editing $*"
	else elvis -G termcap $*
	fi
}

alias dc=cd
alias xd='od --address-radix=x --format=x1'
PS1=`hostname`
PS1="${PS1:0:3}>"
set -o vi

alias ls='ls -h --color=auto' 
